server:
  port: 8100
#配置rabbitMQ服务
spring:
  rabbitmq:
    username: admin
    password: admin
    virtual-host: /
    host: 192.168.71.10
    port: 5672
    listener:
      direct:
        acknowledge-mode: manual #开启手动确认ack 让程序去控制mq的消息的重发删除和转移，防止消息丢失
        retry:
          enabled: true #开启重试
          max-attempts: 3 #最大重试次数
          initial-interval: 2000ms #重试间隔时间
    #addresses: 192.168.71.10:5672集群配置
    publisher-confirm-type: correlated #none 禁止发布确认模式 ，correlated
