spring:
  profiles:
    active: pwd,dev,jdbc
  main:
    ##后定义的覆盖项目中同名的bean
    allow-bean-definition-overriding: true
  application:
    name: sharding-demo
server:
  port: 8084
mybatis-plus:
  mapper-locations: classpath*:*/mappers/*.xml
  typeAliasesPackage: com.snk
  global-config:
    #刷新mapper 调试神器
    refresh: true
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: auto
      field-strategy: 1
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    #\u914D\u7F6EJdbcTypeForNull
    jdbc-type-for-null: 'null'
    #日志输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


